version: "3.8"
services:
    mysql:
        environment:
            - MYSQL_ROOT_PASSWORD=frpsscan
            - MYSQL_DATABASE=frpsscan
            - MYSQL_USER=mysql
            - MYSQL_PASSWORD=mysql
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    rabbit:
        image: rabbitmq
    sub:
        depends_on: 
            - rabbit
            - mysql
        build: ./frpc
        volumes: 
            - ./script.sh:/opt/script.sh
        entrypoint: sh -c 'sleep 5 && amqp-consume -u amqp://rabbit -q "test" -e "amq.topic" -r "worker1" /opt/script.sh'
    add_host:
        depends_on: 
            - rabbit
        build: ./amqp-script
        entrypoint: amqp-publish -u amqp://rabbit -e "amq.topic" -r "worker1" -b
    web:
        depends_on: 
            - mysql
        build: ./www
        ports:
            - "8080:80"
